version: "3.8"

services:
  samba:
    image: samba-ad-dc:latest
    build:
      context: .
      dockerfile: Containerfile
      tags:
        - "samba-ad-dc:latest"
    container_name: samba-ad-dc
    privileged: true
    network_mode: host
    environment:
      TZ: ${TZ}
      SERVER_ROLE: ${SERVER_ROLE:-dc}
      DNS_BACKEND: ${DNS_BACKEND:-SAMBA_INTERNAL}
      REALM: ${REALM}
      DOMAIN: ${DOMAIN}
      DNS_FORWARD: ${DNS_FORWARD:-'1.1.1.1 8.8.8.8'}
      LISTEN_INTERFACES: ${LISTEN_INTERFACES:-'lo'}
    volumes:
      - "${BACKUP_DIR:-./backup}:/backup"
      - "${SHARED_DIR:-./shared}/etc/samba:/etc/samba"
      - "${SHARED_DIR:-./shared}/var/log/samba:/var/log/samba"
      - "${SHARED_DIR:-./shared}/var/lib/samba:/var/lib/samba"
